// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7joUAc3pCwu9HiorHq59tXj6Ew6Pm-Io',
    appId: '1:160700908253:web:your-web-app-id',
    messagingSenderId: '160700908253',
    projectId: 'civic-app-90bbb',
    authDomain: 'civic-app-90bbb.firebaseapp.com',
    storageBucket: 'civic-app-90bbb.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7joUAc3pCwu9HiorHq59tXj6Ew6Pm-Io',
    appId: '1:160700908253:android:bccfcad3f10676f73b9134',
    messagingSenderId: '160700908253',
    projectId: 'civic-app-90bbb',
    storageBucket: 'civic-app-90bbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7joUAc3pCwu9HiorHq59tXj6Ew6Pm-Io',
    appId: '1:160700908253:ios:your-ios-app-id',
    messagingSenderId: '160700908253',
    projectId: 'civic-app-90bbb',
    storageBucket: 'civic-app-90bbb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7joUAc3pCwu9HiorHq59tXj6Ew6Pm-Io',
    appId: '1:160700908253:ios:your-ios-app-id',
    messagingSenderId: '160700908253',
    projectId: 'civic-app-90bbb',
    storageBucket: 'civic-app-90bbb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7joUAc3pCwu9HiorHq59tXj6Ew6Pm-Io',
    appId: '1:160700908253:web:your-web-app-id',
    messagingSenderId: '160700908253',
    projectId: 'civic-app-90bbb',
    authDomain: 'civic-app-90bbb.firebaseapp.com',
    storageBucket: 'civic-app-90bbb.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
